project:
  type: website

website:
  title: "Notes of a Dabbler"
  site-url: https://timely-narwhal-1c7288.netlify.app/
  navbar:
    right:
      - about.qmd
      - icon: rss
        href: index.xml
      - icon: github
        href: https://github.com/notesofdabbler
format:
  html:
    theme: cosmo
    css: styles.css



